# This file stores the flash_commands for each mcus
# Previous version KCONFIG_CONFIG was needed now it is automaticly added when make flash is called
# version : 0.1
# tested/supported flash methods :
#  - make flash
#  - sdcard_flash
#  - flashtool.py
#  - mount/cp/umount (for rp2040)

[mcu T0]
klipper_section: mcu T0
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u 225077e58121

[mcu T1]
config_name: mcu T0
klipper_section: mcu T1
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u 53843a489822

[mcu T2]
config_name: mcu T0
klipper_section: mcu T2
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u 9ddf448c6f86

[mcu T3]
config_name: mcu T0
klipper_section: mcu T3
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u b608fe976d0f

[mcu T4]
config_name: mcu T0
klipper_section: mcu T4
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u 08452c0dce7a
